# Generated by Django 4.1.3 on 2022-12-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=25)),
                ('antiguedad', models.IntegerField()),
                ('cargo', models.CharField(max_length=50)),
                ('breve_descripcion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
